package com.velocityappsdj.gcal.common

import com.velocityappsdj.gcal.network.model.response.Event
import com.velocityappsdj.gcal.network.model.response.Start

val dummyEvents = listOf(
    Event(
        start = Start("2024-06-20T10:00:00Z", "UTC"),
        summary = "Event 1",
        attachments = null,
        attendees = null,
        conferenceData = null,
        created = null,
        creator = null,
        description = null,
        end = null,
        etag = null,
        eventType = null,
        guestsCanInviteOthers = null,
        guestsCanModify = null,
        hangoutLink = null,
        htmlLink = null,
        iCalUID = null,
        id = null,
        kind = null,
        location = null,
        organizer = null,
        originalStartTime = null,
        privateCopy = null,
        recurringEventId = null,
        reminders = null,
        sequence = null,
        status = null,
        updated = null
    ),
    Event(
        start = Start("2024-05-21T12:00:00Z", "UTC"),
        summary = "Event 2",
        attachments = null,
        attendees = null,
        conferenceData = null,
        created = null,
        creator = null,
        description = null,
        end = null,
        etag = null,
        eventType = null,
        guestsCanInviteOthers = null,
        guestsCanModify = null,
        hangoutLink = null,
        htmlLink = null,
        iCalUID = null,
        id = null,
        kind = null,
        location = null,
        organizer = null,
        originalStartTime = null,
        privateCopy = null,
        recurringEventId = null,
        reminders = null,
        sequence = null,
        status = null,
        updated = null
    ),
    Event(
        start = Start("2024-05-01T09:00:00Z", "UTC"),
        summary = "Event 3",
        attachments = null,
        attendees = null,
        conferenceData = null,
        created = null,
        creator = null,
        description = null,
        end = null,
        etag = null,
        eventType = null,
        guestsCanInviteOthers = null,
        guestsCanModify = null,
        hangoutLink = null,
        htmlLink = null,
        iCalUID = null,
        id = null,
        kind = null,
        location = null,
        organizer = null,
        originalStartTime = null,
        privateCopy = null,
        recurringEventId = null,
        reminders = null,
        sequence = null,
        status = null,
        updated = null
    ),
    Event(
        start = Start("2024-05-01T09:00:00Z", "UTC"),
        summary = "Event 4",
        attachments = null,
        attendees = null,
        conferenceData = null,
        created = null,
        creator = null,
        description = null,
        end = null,
        etag = null,
        eventType = null,
        guestsCanInviteOthers = null,
        guestsCanModify = null,
        hangoutLink = null,
        htmlLink = null,
        iCalUID = null,
        id = null,
        kind = null,
        location = null,
        organizer = null,
        originalStartTime = null,
        privateCopy = null,
        recurringEventId = null,
        reminders = null,
        sequence = null,
        status = null,
        updated = null
    )
)

val dummyGroupedEvents = mapOf(
    "2024-06" to listOf(dummyEvents[0]),
    "2024-05" to listOf(dummyEvents[1], dummyEvents[2], dummyEvents[3]),
)